name: Build other OS Binaries

on:
  release:
    types: [published]

jobs:
  build-mac-os:
    runs-on: 'self-hosted-macos'
    steps:
      - uses: actions/checkout@v4
      - name: "Install Dependencies"
        run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install python3.12 lua gobject-introspection cairo p7zip wget glib xz
      - name: "Build Archipelago"
        run: |
        python3.12 -m venv venv
        source venv/bin/activate
        python3.12 -m pip install --upgrade pip "PyGObject<3.51.0" charset-normalizer
        python3.12 setup.py build_exe --yes bdist_appimage --yes
        echo -e "setup.py build output:\n `ls build`"
        echo -e "setup.py dist output:\n `ls dist`"
        export TAR_NAME="Archipelago-macOS-Sequoia.tar.gz"
        (cd build && DIR_NAME="`ls | grep exe`" && mv "$DIR_NAME" Archipelago && tar -cv Archipelago | gzip -8 > ../dist/$TAR_NAME && mv Archipelago "$DIR_NAME")
        echo "TAR_NAME=$TAR_NAME" >> $GITHUB_ENV
      - name: Build Again
        run: |
          source venv/bin/activate
          python setup.py build_exe --yes
      - name: Check build loads expected worlds
        shell: bash
        run: |
          cd build/exe*
          mv Players/Templates/meta.yaml .
          ls -1 Players/Templates | sort > setup-player-templates.txt
          rm -R Players/Templates
          timeout 30 ./ArchipelagoLauncher "Generate Template Options" || true
          ls -1 Players/Templates | sort > generated-player-templates.txt
          cmp setup-player-templates.txt generated-player-templates.txt \
            || diff setup-player-templates.txt generated-player-templates.txt
          mv meta.yaml Players/Templates/
      - name: Test Generate
        shell: bash
        run: |
          cd build/exe*
          cp Players/Templates/VVVVVV.yaml Players/
          timeout 30 ./ArchipelagoGenerate
      - name: Store .tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TAR_NAME }}
          path: dist/${{ env.TAR_NAME }}
          compression-level: 0  # .gz is incompressible by zip
          if-no-files-found: error
          retention-days: 7
